### ISSUE TITLE
I'm sure it's got to be a false positive, but...

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/CQMacroCreator#10]
Microsoft Security Essentials is blocking me from downloading this because it thinks it's a Trojan names Spursint.F!cl

I did a quick search and came across this
https://gitlab.com/gitlab-org/gitlab-runner/issues/2564
"because the binary is not signed. I'm curious if this is the reason also this time.
I don't remember the issue number at this moment but we're already discussing how to work on binaries and packages signing."

I have no idea what that means. Why wouldn't I be shocked if because I asked that the versions be updated, I just FUBAR'd everything?.....

**Comment by Alya-N** [comment]
Weird... I'll try reuploading it, but the binary I have seems fine.
I'll check the file it gives first though, to see if it gives a trojan warning.
EDIT: It doesn't, just the standard "Do you wish to run this file, it's from an unknown publisher"

**Comment by Vitae666** [comment]
Dunno :(

Category: Trojan
Description: This program is dangerous and executes commands from an attacker.
Recommended action: Remove this software immediately.
Items: 
file:C:\Users\jweiss\Desktop\fe386ba6-a188-4ed1-a001-5ac2b8860115.tmp
Get more information about this item online.

The "Get more info" link leads me to a non-working Microsoft page to boot. ROFL!

I just told MSE to fuck off and allow it to download.
Don't know why MSE suddenly doesn't like it. Like I said, I don't know what is meant by "binaries and packages signings"

Now that I think about it, I shouldn't have told it to allow it yet. Should have tried to download 4.1a 1st to see if I got the error there as well. Would mean for sure that something weird happened with 4.1b.
Dang :(

**Comment by Alya-N** [comment]
You can still try to do that, I guess.

**Comment by Alya-N** [comment]
https://github.com/Alya-N/CQMacroCreator/tree/20fe9d3e6246fad9263d8f6619c0cf7a97d23fda
right before the commit

**Comment by Vitae666** [comment]
Ok, found how to remove the "Allow"
I downloaded 4.1a and no alert. Tried to download 4.1b again and got the same trojan warning.
I don't know why 4.1b is having this problem with MSE!
But it's damned sure there's a trojan in there. 
I scanned it with Kaspersky after I allowed it again, and it says it's clean.
*mutter*
Some how, I'm almost betting it's the changes to the Assembly bit. Wouldn't shock me that MSE has an issue somehow there.

**Comment by Alya-N** [comment]
Strange...
For me it only gives the virus warning under 2 conditions:
1. I am using chrome
2. I am downloading the .exe separately, and not the whole .zip file

Was fine on Firefox

**Comment by Vitae666** [comment]
Whelp, I'm using Chrome and downloading just the .exe file. Which is the only way I've ever done it.
But again, 4.1a gives no warning. Just 4.1b. Just checked 3 times total just to make sure.
And other than the usual code changes, the only "new and different" thing is the changes to AssemblyInfo.cs
But I don't see how that would do it.

Note that I am in no way saying that there IS a virus in it suddenly. Just saying that I have no damned clue as to what the hell is the diff between 4.1a and 4.1b that is making this popup. And my only thought is AssemblyInfo.cs being the possible cause. Which I'm betting isn't it at all :)

**Comment by Alya-N** [comment]
Somehow, before I downloaded it from Chrome, scanning the macros didn't show a virus, but now that I downloaded it, it blocked me from using any macrocreator... (Easily fixable, but annoying)
Now I can't test it for false positives, but I really want to blame Chrome for this.

**Comment by Vitae666** [comment]
Any chance I can ask you to do a test of reverting just AssemblyInfo.cs and recompiling to an .exe so I can see if I get the error when downloading still?
Wouldn't be able to test for a few hours tho. WAAAAAY past my bedtime and need to be up in 2hrs :)

**Comment by Alya-N** [comment]
Tomorrow, sure, I'll make a version just for you.

**Comment by Vitae666** [comment]
Thanks 
*bow*

**Comment by Alya-N** [comment]
Try now, I uploaded a new version.

**Comment by Vitae666** [comment]
Still happening.
But you didn't revert AssemblyInfo.cs to the original file.
https://github.com/Alya-N/CQMacroCreator/blob/42e21acb7da51efa2c27fbfface860d5568d4b05/CQMacroCreator/Properties/AssemblyInfo.cs

Like I said, would need to have that file to fully do the QA.
Also, note line 23
[assembly: Guid("ebd43ff0-b4a9-4ace-a48e-f28195ba005b")]

It's possible that maybe the 
```
[assembly: AssemblyVersion("3.0.7.*")]
[assembly: AssemblyFileVersion("3.0.7.*")]
```
is tied to that.

https://en.wikipedia.org/wiki/Universally_unique_identifier

I'm clueless about that stuff, but like I mentioned, the only file that was changed recently that wasn't among the usual files was that one.
It might not be it at all, but step on in QA is to go back and change back what was changed :)

**Comment by Alya-N** [comment]
I've reverted it, try the file here: 
https://github.com/Alya-N/CQMacroCreator/tree/Fairies

**Comment by Alya-N** [comment]
did it work?
I'll merge to master branch if it did
https://github.com/Alya-N/CQMacroCreator/tree/Fairies

**Comment by Vitae666** [comment]
I cleared the Allowed setting. 
Just to test, downloaded 4.1a no warning. 
Tried to redownload 4.1b and got the virus warning.
Downloaded 4.1c (original upload) got the warning.
Downloaded the newest 4.1c from your link and no warning.
Which is a good thing!

Tested this whole loop 3 times just to be sure I had consistent responses.
Sorry about the delay, that's why it took me so long. 

So, with my limited knowledge of coding, I have to think that maybe I was right in that changing the AssemblyInfo.cs was the cause.
**BUT** I have no damned clue how that is tho. I've checked the history of that file and the version #'s in it change, but that ID # stays exactly the same.
Why changing that file does anything I don't know. Much less what causes it to throw a virus warning!
I guess, at this point, my idea about making it easier to see the versions on the file hover was stupidity personified :)

BTW, there's no version # listed on the Creator.
Like, how the Calc shows it 1st thing, and the Claimer has it on the upper right.
There's nothing on the Creator.
If no one else can figure out what the hell's up with the Assembly bit, maybe something on there next to your name?

**Comment by Alya-N** [comment]
Thank you. I'll try to figure it out eventually, but the version number changes here: http://prntscr.com/mfqzoo

**Comment by Vitae666** [comment]
Kewl. Don't see that in the last one I downloaded (From the link). I'll get the latest now :)

Considering Assembly is in a folder by itself with 4 other files, maybe those all tie together somehow.
But I don't know. Just another guess.

**Comment by AdrianTeng** [comment]
Somehow this commit `bafa247083f0fd416a6b5cea0c49727779d96b43` reintroduce the "trojan"

**Comment by Vitae666** [comment]
Are you talking about 4.1c? Cause afaik that ones clean. 4.1b would give
the trojan. But when Alya reverted the assembly file it stopped. For me at
least.

**Comment by Vitae666** [comment]
Shit! Just tried to download the latest 4.1c and I'm getting the trojan warning again! Don't know why!
Downloaded it 3 times 12hrs ago and it was perfectly fine.

**Comment by AdrianTeng** [comment]
I've been going down the commit tree from `HEAD` and download each `exe` and see which version would / would not trigger the alert. Commits above and incl `bafa247083f0fd416a6b5cea0c49727779d96b43` would trigger the warning. Anything older than that wouldn't

**Comment by Alya-N** [comment]
So, for you it only appeared after I reverted the version number in the assembly?
Strange, since that would mean that the versions that give virus alerts are different for both of you.
Since the assembly change didn't work, I have no idea where to start, since other changes were essential, like adding promos to hero files and preventing autoDQ crash due to it expecting promo info. You can check the commits for any changes I've made.
Strangely enough, I didn't get a virus warning even when scanning with Windows Defender, until I tried to download it from Chrome rather than Firefox. Then every MacroCreator file was blocked.

**Comment by Vitae666** [comment]
That's what's weird for me. A was fine. B was fubard. C with the reverting
of assembly was fine and then when I redownloaded it after the new virus
post it was fubard as well.
Which makes no sense because I downloaded the same version that I had done
12hrs before.

**Comment by thodan110** [comment]
I am having the same problem with E. D & C downloaded fine.

**Comment by Vitae666** [comment]
> Thank you. I'll try to figure it out eventually, but the version number changes here: http://prntscr.com/mfqzoo

BTW, I was confused by this until now. Didn't know if the version # display was an upcoming thing or what. And just realized it's yet another one of those things that only seems to work if I do that silly Performance with Visual Styles thing. The thing that lets the app have some areas be actually visible.

**Comment by Vitae666** [comment]
Closing this cause no one's said anything about this since March. 
Don't know if everyone who had problems added an exception (like me) or what.
Or maybe it Microsoft realized the mistake....yeah....right :)

**Comment by Vitae666** [comment]
Closing this cause no one's said anything about this since March.
Don't know if everyone who had problems added an exception (like me) or what.
Or maybe it Microsoft realized the mistake....yeah....right :)
