### ISSUE TITLE
Added code for autoDQ

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/CQMacroCreator#11]
Heck is autoDQ? Wasn't it doing that before?
Really need updated Readme files so we know what the heck is going on :(

**Comment by Alya-N** [comment]
There was apparently a rare crash happening, the issue is still being diagnosed, but the lack of promos could have been the issue.
EDIT: I might work on the Patch Notes for MacroCreator as well. Not now, season start will be busy.

**Comment by Vitae666** [comment]
Don't know what the code added for AutoDQ was, or what crash was happening, but seems that DQ is not working at all now.

![image](https://user-images.githubusercontent.com/9310914/52181248-ec673600-27bd-11e9-89e2-700da724df95.png)

**Comment by Alya-N** [comment]
Pretty sure that's because the servers are not working well right now. I've been testing autoDQ for the past few days without crashes and it got past the last solvable DQ.

**Comment by Vitae666** [comment]
Ah. Well I'm screwed then. Just left for work. So unless dq is up for the
next 10hrs I'm gonna miss out 😥
