### ISSUE TITLE
New Quests ARe Broken

### ISSUE THREAD

**Issue by robgw84** [Alya-N/CQMacroCreator#16]
The new quests in the macro creator are a bit bugged, even if you have done some of them the boxes for them wont activate on their own or by clicking the Get Quests button. And if you click the boxes yourself and hit "Add" then the Add button below them becomes greyed out permanently even if you deselect the boxes.

**Comment by Alya-N** [comment]
Sorry, I forgot to change a variable and couldn't test the server features. It should be fixed in v4.1h.

**Comment by robgw84** [comment]
Ok.
