### ISSUE TITLE
save quests and heroes

### ISSUE THREAD

**Issue by Stefanosdl** [Alya-N/CQMacroCreator#17]
It doesn't save the completed quests and the heroes that i add.

**Comment by Alya-N** [comment]
I don't think quests can be saved, unless you use the server integration.
Heroes, however, can be saved, by using the **"Hero Files"** function in the **"Other"** tab.
If you want your heroes to be loaded by default, but without connecting your macrocreator to the game:
1. Click **"Help me create MacroSettings file"** in the **"Other"** tab 
2. Change **"Default action on start"** to **"1 - Load heroes from defaultHeroes file"** 
3. Save your hero setup through **"Other" -> "Hero Files" -> "Save File"** 
4. Name it **defaultHeroes** and place it in the same folder as calc and macrocreator.

(if you do want to get data from the game automatically, **"I don't know how to get my Auth Ticket..."** in the **SettingsHelper** should lead to a guide on setting it up.)
