### ISSUE TITLE
Macro Creator wont load.

### ISSUE THREAD

**Issue by robgw84** [Alya-N/CQMacroCreator#22]
I downloaded the latest update and now the Macro Creator wont run. Trying to run it will cause a process to run in Task Manager, but nothing happens. And I cant close the process either, I now have half a dozen processes going for it, luckily they aren't using much memory so its not a huge issue, but not being able to close them is a problem.

**Comment by Alya-N** [comment]
Is there anything in the error/exception logs? (they usually appear in the same folder if something goes wrong) 
I guess it might have something to do with the recent int32 limit fix on the follower count though. If that's the case, I'm not sure if it's possible to fix it while keeping the follower limit above int32.

**Comment by robgw84** [comment]
I went back to the previous version just before the newest and that worked, I don't have over 2 billion followers yet though, 230mil at the moment.
As for the logs, this is all the error log said for yesterday, not sure if any of these happened with the newest version though
13/05/2019 10:53:17 AM
13/05/2019 10:53:20 AM
    Error Cloud Script Error: send WB {"ok":false,"err":"Wait 5 seconds"}
13/05/2019 2:38:43 PM
13/05/2019 2:38:46 PM
    Error Cloud Script Error: status PlayFab.ClientModels.ExecuteCloudScriptResult
13/05/2019 8:47:59 PM
13/05/2019 8:48:03 PM
    Error Cloud Script Error: Claim All PlayFab.ClientModels.ExecuteCloudScriptResult
Exception logs there is nothing since Feb 5th in there.
I don't know if anything would show in the logs though, because it never opened up. However every time I tried to run it a process would launch in Task Manager, but I was unable to close those processes which prevented me from changing to the older version because it believed that it was still running. Even logging out of my account on my pc didn't help because it was also launching processes for all users, so I had to restart my pc to get those processes to shut down so I could install the older version.
The processes it launched though only used 112 or 112K (cant remember if it showed the K beside it or not) memory each.
    On Tuesday, May 14, 2019, 2:10:20 p.m. ADT, Alya-N <notifications@github.com> wrote:  
 
 
Is there anything in the error/exception logs? (they usually appear in the same folder if something goes wrong)
I guess it might have something to do with the recent int32 limit fix on the follower count though. If that's the case, I'm not sure if it's possible to fix it while keeping the follower limit above int32.

**Comment by Alya-N** [comment]
Just to clarify, this is the previous version you're talking about, right? https://github.com/Alya-N/CQMacroCreator/tree/30b237c4b01cf7ba3ae7a637bc900997d5f665d2
And, so far, I haven't been able to find what went wrong. If the version above works, then it'll possibly narrow down where the error occurred.

**Comment by robgw84** [comment]
Yeah that seems to be the one I tried, that did work for me. It was just the newest version that would not start. I have no idea what happened either, I just know that it wasn't an issue with something else I had running because I had to restart 3 times so there was nothing else running besides the usual windows stuff.
