### ISSUE TITLE
Max Hero Amount for Quests

### ISSUE THREAD

**Issue by A69Tor** [Alya-N/CQMacroCreator#24]
This is a suggestion, not an issue.  Would it be possible to implement a "Only use X" heroes, option for when running promo quests, so that way you can keep your X total heroes selected in the pool, but limit it to using 3 heroes for the quest run?

**Comment by Alya-N** [comment]
That's a calc suggestion, but there is already something that limits hero amount to 3 (questXXX-4), but it doesn't force a hero to be in the solution, so it's not exactly that useful for promo quests.
