### ISSUE TITLE
Order of Retia and Newt

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/CQMacroCreator#26]
Order of Retia and Newt are off I think. For Daily 79 I have Retia in game, but CQMC is saying I have Newt.
![image](https://user-images.githubusercontent.com/9310914/66013628-e6833b00-e499-11e9-9daf-24d5dfee99a3.png)

**Comment by Alya-N** [comment]
Oh, my bad, I forgot to add bornag to the hero server id. Will do in the next patch, shouldn't take too long.

**Comment by Vitae666** [comment]
Thank you :)
