### ISSUE TITLE
The new heroes aren't being added to the total hero used count.

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/CQMacroCreator#28]
I have 152 heroes, but show "Currently selected heroes count: 147"

**Comment by Vitae666** [comment]
Bump. Astro's aren't counted.

**Comment by Alya-N** [comment]
Maybe I'm closing it too late, but I just checked all Christmas heroes and Astronauts, and they are being counted in the selected hero count. All the new heroes as well.
