### ISSUE TITLE
Can the Max Time in Macro Creator be set in Settings?

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/CQMacroCreator#31]
There's a LOT of times where I'll wake up and/or come back from work, and the DQ's been running on the same 1 DQ for HOURS. 
Can we have something in Macro Settings that you can set the time you want and when you open CQMC it's set and not showing -1?
Like, normally, if I use MC directly, I'll set it for 180 seconds. So, when I use CQA, it can use that as well and not be running for 11hrs pulling my CPU. The other day I woke up, went to work, came back, went to sleep, woke up and there was less than 2hrs before the next DQ. So, it was running for 22hrs.

**Comment by Alya-N** [comment]
There has already been a thread about that, actually, thanks for the reminder: #23
Still not sure if I'll be able to add any QoL changes to MacroCreator any time soon.
The calc shouldn't normally run for hours though, maximum 5 minutes. 
While it isn't a feature yet, I'd recommend adjusting the follower range to use the 4 highest tier monsters, and limiting your hero count to 25 maximum, so it doesn't run as long.

**Comment by Vitae666** [comment]
It's been added to Matt's version.
