### ISSUE TITLE
Size issues

### ISSUE THREAD

**Issue by Farario** [Alya-N/CQMacroCreator#6]
I'm on a laptop, and I can't access the bottom of the gui to get at the last quests, or the ascended chest heroes and such. It just cuts off without the option of scrolling further. The scroll bar won't go down past where it is in the picture. Resizing the window does nothing to help, just cuts it off even earlier.
<img width="658" alt="1" src="https://user-images.githubusercontent.com/43454642/50359144-f8739d00-055b-11e9-960c-72bfa860987b.png">

**Comment by Alya-N** [comment]
We are aware of this issue and it is being currently worked on by monsenanna. Thank you for making a post about it.

**Comment by Alya-N** [comment]
The new v4.0d version of macrocreator is now 720p-friendly.
