### ISSUE TITLE
Not an issue, just a question/request

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/CQMacroCreator#8]
For the program, when you hover over it, it shows File Version: 3.0.7.0 and the same in the Properties.
Can you fix that when you update?
I know for CQAF it changes to the current version (minus the letter for some reason). No idea why/how tho :)
I DO see that for CQMC there's
```
[assembly: AssemblyVersion("3.0.7.*")]
[assembly: AssemblyFileVersion("3.0.7.*")]
```
in AssemblyInfo.cs but I got not idea if that's used.
Just easier, at least for me, to hover over the file and see if I actually got the latest version.
Heck, CosmosQuest.exe don't even have a file version on hover or properties. Be nice there too so I don't have to run it just to see the version I have ;-)

**Comment by Alya-N** [comment]
Thank you, this has been fixed among other small changes to MacroCreator in the latest patch.
